permissions:
  contents: write # Required for pushing to gh-pages branch

name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build project
        env:
          VITE_GOOGLE_API_KEY: ${{ secrets.VITE_GOOGLE_API_KEY }}
          VITE_GOOGLE_CLIENT_ID: ${{ secrets.VITE_GOOGLE_CLIENT_ID }}
          VITE_GOOGLE_DRIVE_ISSUES_FOLDER_ID: ${{ secrets.VITE_GOOGLE_DRIVE_ISSUES_FOLDER_ID }}
          VITE_GOOGLE_DRIVE_PDFS_FOLDER_ID: ${{ secrets.VITE_GOOGLE_DRIVE_PDFS_FOLDER_ID }}
        run: |
          npm run build # Replace with your build script
          cp dist/spa/index.html dist/spa/404.html
          # Remove PDF files to reduce deployment size
          find dist/spa -name "*.pdf" -type f -delete
          # Create a simple .nojekyll file to prevent GitHub from processing the site with Jekyll
          touch dist/spa/.nojekyll

      - name: Deploy to GH Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/spa # Replace with your build output directory
